bind=ALT,a,spawn, ~/.config/mango/typechar.sh à À
bind=ALT+SHIFT,a,spawn, ~/.config/mango/typechar.sh À à

bind=ALT,e,spawn, ~/.config/mango/typechar.sh è È
bind=ALT+SHIFT,e,spawn, ~/.config/mango/typechar.sh È è

bind=ALT,i,spawn, ~/.config/mango/typechar.sh ì Ì
bind=ALT+SHIFT,i,spawn, ~/.config/mango/typechar.sh Ì ì

bind=ALT,o,spawn, ~/.config/mango/typechar.sh ò Ò
bind=ALT+SHIFT,o,spawn, ~/.config/mango/typechar.sh Ò ò

bind=ALT,u,spawn, ~/.config/mango/typechar.sh ù Ù
bind=ALT+SHIFT,u,spawn, ~/.config/mango/typechar.sh Ù ù

bind=ALT,s,spawn, ~/.config/mango/typechar.sh ß SS
bind=ALT+SHIFT,s,spawn, ~/.config/mango/typechar.sh SS ß
