shell_integration disabled

cursor_trail 1
background_opacity 0.8
paste_actions confirm-if-large
draw_minimal_borders yes
placement_strategy top-left
clipboard_control write-clipboard write-primary read-clipboard read-primary
notify_on_cmd_finish unfocused

map ctrl+shift+home no_op
map ctrl+shift+end no_op
map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+up no_op
map ctrl+shift+down no_op

map ctrl+shift+n new_os_window_with_cwd

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
